// CREER LIST
export const CREER_LIST_START="CREER_LIST_START";
export const CREER_LIST_SUCCESS="CREER_LIST_SUCCESS";
export const CREER_LIST_FAILED="CREER_LIST_FAILED";

export const CREER_LIST_STATUS_CANCEL="CREER_LIST_STATUS_CANCEL";

export const GET_LIST_START="GET_LIST_START";
export const GET_LIST_SUCCESS="GET_LIST_SUCCESS";
export const GET_LIST_FAILED="GET_LIST_FAILED"; 

export const DELETE="DELETE";

export const SEEITEM = "SEEITEM"; 
export const EDİTİTEM = "EDİTİTEM";  
export const UPDATELİSTSERVİCE = "UPDATELİSTSERVİCE";  